-- MySQL Script generated by MySQL Workbench
-- Thu Jan 20 08:38:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Geres4UDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Geres4UDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Geres4UDB` DEFAULT CHARACTER SET utf8 ;
USE `Geres4UDB` ;

-- -----------------------------------------------------
-- Table `Geres4UDB`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Geres4UDB`.`Client` (
  `Email` VARCHAR(150) NOT NULL,
  `Password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Geres4UDB`.`Reviser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Geres4UDB`.`Reviser` (
  `Email` VARCHAR(150) NOT NULL,
  `Password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Geres4UDB`.`PointOfInterest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Geres4UDB`.`PointOfInterest` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(64) NOT NULL,
  `Images` VARCHAR(2048) NULL,
  `Lat` DOUBLE NOT NULL,
  `Long` DOUBLE NOT NULL,
  `isSugestion` TINYINT NOT NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Geres4UDB`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Geres4UDB`.`Category` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Geres4UDB`.`PointOfInterestCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Geres4UDB`.`PointOfInterestCategory` (
  `CategoryID` INT NOT NULL,
  `PointOfInterestID` INT NOT NULL,
  INDEX `fk_PointOfInterest Category_PointOfInterest1_idx` (`PointOfInterestID` ASC) VISIBLE,
  PRIMARY KEY (`CategoryID`, `PointOfInterestID`),
  CONSTRAINT `fk_PointOfInterest Category_Category1`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `Geres4UDB`.`Category` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PointOfInterest Category_PointOfInterest1`
    FOREIGN KEY (`PointOfInterestID`)
    REFERENCES `Geres4UDB`.`PointOfInterest` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Geres4UDB`.`ClientHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Geres4UDB`.`ClientHistory` (
  `ClientID` VARCHAR(150) NOT NULL,
  `PointOfInterestID` INT NOT NULL,
  INDEX `fk_ClientHistory_Client1_idx` (`ClientID` ASC) VISIBLE,
  INDEX `fk_ClientHistory_PointOfInterest1_idx` (`PointOfInterestID` ASC) VISIBLE,
  PRIMARY KEY (`ClientID`, `PointOfInterestID`),
  CONSTRAINT `fk_ClientHistory_Client1`
    FOREIGN KEY (`ClientID`)
    REFERENCES `Geres4UDB`.`Client` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClientHistory_PointOfInterest1`
    FOREIGN KEY (`PointOfInterestID`)
    REFERENCES `Geres4UDB`.`PointOfInterest` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;