INSERT INTO `geres4udb`.`reviser` (`Email`, `Password`) VALUES ('admin@geres4u.pt', 'admin');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('Cascata');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('Lagoa');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('Miradouro');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('Grutas');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('Passadicos');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('Ponte');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('ArteRupestre');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('Espigueiros');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('Ecovia');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('EdificioRestauracao');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('Termas');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('Aldeias');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('Monumentos');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('EdificioReligioso');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('PraiaFluvial');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('ParqueLazer');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('ParqueNatural');
INSERT INTO `geres4udb`.`category` (`Name`) VALUES ('Trilhos');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Cascata do Arado', 'cascataarado.png', '41.723994530811034', '-8.129598492662442', '0', 'Cascata com uma poça. Frequentada por diversos turistas.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Miradouro da Pedra Bela', 'mirapedrabela.png', '41.71596781096567', '-8.1532046307703', '0', 'Miradouro com uma vista para um rio fantástica.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Cascata de S. Miguel, Portela do Homem', 'cascatasmiguelphomem.png', '41.80382891983318', '-8.128166201930865', '0', 'Cascata com alguma força. Dos pontos mais bonitos do Gerês.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Santuário S. Bento da Porta Aberta', 'santsbentopaberta.png', '41.6903318440133', '-8.203583994013254', '0', 'Santuário muito movimentado. Famoso pelas viagens a pé até ele.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Ponte da Misarela', 'pontemisarela.png', '41.692815529749005', '-8.019571205894989', '0', 'Erguida na Idade Média. Considerada Imóvel de Interesse Público desde 1993. Reza a lenda que esta foi construída pelo Diabo.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Ecovia do Vez', 'ecoviavez.png', '41.97376115395846', '-8.374237015415572', '0', 'Ecovia, por vezes em madeira que, ao longo de cerca de 30 Km une Santar, Arcos De Valdevez e a Aldeia de Sistelo.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Santuário de Nossa Senhora da Peneda', 'santsenhorapeneda.png', '41.974645938459794', '-8.223086201925408', '0', 'Santuário católico dedicado à Virgem Maria sob a invocação de Nossa Senhora da Peneda.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Parque Porta do Mezio', 'parqportamezio.png', '41.885114028428156', '-8.31313061727472', '0', '3 hectares plenos de espaços para pequenos e graúdos.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Castelo de Lindoso', 'castelolindoso.png', '41.86733969063786', '-8.199121401928824', '0', 'Castelo erguido de raiz, na Idade Média, com a função de vigia, defesa e marco de soberania. Nunca esteve envolvido em grandes batalhas, mas é considerado como um dos mais importantes monumentos militares portugueses.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Cascatas de Fecha de Barjas', 'cascatasfechabarjas.png', '41.703942721140024', '-8.109572101934036', '0', 'Cascata de alta montanha cujas águas são provenientes do Rio Arado e onde só se pode chegar por caminhos pedestres dada a grande dificuldades de acesso ao local visto os caminhos serem muito sinuosos e agrestes.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Poço Negro', 'poconegro.png', '41.87847109195984', '-8.25721688843833', '0', 'Lagoa azul natural de águas cristalinas, praia fluvial selvagem do Rio Teixeira (afluente do Rio Vouga) que tem a sua nascente um pouco mais acima. ');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Serra do Gerês', 'serrageres.png', '41.82570267100256', '-8.04098228619744', '0', 'Segunda maior elevação de Portugal Continental. O cume atinge 1546 metros de altitude (Pico da Nevosa, na fronteira com a Galiza).');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Espigueiros do Soajo', 'espigueirossoajo.png', '41.872530605300796', '-8.262201128908954', '0', 'Compõem uma eira comunitária constituída por 24 espigueiros, todos em pedra e assentes num afloramento de granito. O mais antigo data de 1782. Alguns destes espigueiros são ainda hoje utilizados pela população.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Barragem da Caniçada', 'barragemcanicada.png', '41.653249157835184', '-8.059713746116756', '0', 'Barragem em arco em betão com uma altura de 76 m acima da fundação e um comprimento de coroamento de 246 m. ');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Cascata de Pincães', 'cascatapincaes.png', '41.71577668575353', '-8.059713746116756', '0', 'Uma das mais belas cascatas e uma das mais visitadas do Parque Nacional da Peneda-Gerês. A queda de água precipita-se de uma altura de cerca de 20 metros, alimentando uma pequena lagoa de água translucida.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Parque das Termas', 'parquetermas.png', '41.73069634931102', '-8.162022367279702', '0', 'Parque agradável de médias dimensões, bonito local para fazer um piquenique. Custa um euro por pessoa.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Serra Amarela', 'serraamarela.png', '41.80178204201952', '-8.217671693634928', '0', 'Nona maior elevação de Portugal Continental, com 1359 metros de altitude. Situa-se no Minho, entre a serra do Gerês e a serra do Soajo.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Serra do Soajo', 'serrasoajo.png', '41.930096733374555', '-8.291818332183338', '0', 'Sexta mais alta serra de Portugal Continental, com 1416 m de altitude e 768 m de proeminência topográfica. O seu pico, designado por Pico da Pedrada, é o mais alto do distrito de Viana do Castelo.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Pé de Cabril', 'pecabril.png', '41.76668454024771', '-8.157395528912346', '0', 'É a 12ª montanha mais alta da serra do Gerês e o seu cume um dos mais visíveis e facilmente reconhecido. No seu topo a vista é magnífica.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Rio Arado', 'rioarado.png', '41.7265266305494', '-8.130853632287604', '0', 'Rio que nasce na envolvente do Curral do Camalhão.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Castelo de Castro de Laboreiro', 'castelocastrolab.png', '42.02271273280908', '-8.158018871230906', '0', 'Construído na Idade Média, de arquitetura românica, apresenta padrões góticos expressos na integração de cubelos e pequenos torreões nos panos da muralha da alcáçova. Foi classificado Monumento Nacional em 1944.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Mata da Albergaria', 'mataalbergaria.png', '41.79308554927323', '-8.147631344257961', '0', 'Um dos bosques mais representativos dos carvalhais galaico-portugueses de Quercus robur e Quercus pyrenaica. Apresenta ainda um troço da via romana Geira.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Cascata de Cela Cavalos', 'cascatacelacavalos.png', '41.7611747706525', '-7.986993917278693', '0', 'Refúgio perfeito para relaxar a dois. Encontra-se escondida entre Cela e Lapela, dois povoados de montanha, localizados no Concelho de Montalegre.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Minas dos Carris', 'minascarris.png', '41.81206147042844', '-8.045541730767226', '0', 'São um complexo mineiro abandonado. Tinham como objetivo a exploração do volfrâmio.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Poço Azul', 'pocoazul.png', '41.73365620672695', '-8.10696181727955', '0', 'Obra inacabada da Natureza. É um refúgio em construção há milhares de anos e que está em permanente evolução. Oferece o encanto selvagem de uma piscina natural e a frescura da água da ribeira.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Branda da Aveleira', 'brandaaveleira.png', '41.99516448345177', '-8.28037838212594', '0', 'Vocacionada para o Turimo Rural e de Montanha. Proporciona aos seus visitantes variadas possibilidades para que, desfrutem de uma magnífica estadia nestes alojamentos.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Mosteiro de Santa Maria das Únias', 'mosteirosantamariaunias.png', '41.83133661658155', '-7.942543601929986', '0', 'Mosteiro em ruínas localizado nos arredores de Pitões das Júnias.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Barragem do Alto-Lindoso', 'barragemaltolindoso.png', '41.87236822936386', '-8.2028314865822', '0', 'Maior e mais potente produtor hidroeléctrico em Portugal. É uma das mais altas construções de Portugal.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Cascata de Leonte', 'cascataleonte.png', '41.76092895364981', '-8.149215530768872', '0', 'Forma-se com o despenhar das águas do ribeiro da Taleira, do alto de uma penedia de rocha granítica a 19 metros, no leito do Rio Gerês. Sendo que, em verões com períodos de seca, o caudal da cascata pode desaparecer.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Serra da Cabreira', 'serracabreira.png', '41.64993543446599', '-8.052136401633868', '0', 'Elevação de Portugal Continental, com 1262 metros de altitude, no Alto do Talefe.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Espigueiros de Lindoso', 'espigueiroslindoso.png', '41.866449593752584', '-8.199837488438712', '0', 'Eira composta por 50 espigueiros dos séculos XVII e XVIII, apresentando um aglomerado único no país e de rara beleza.');
INSERT INTO `geres4udb`.`pointofinterest` (`Name`, `Images`, `Lat`, `Long`, `isSugestion`, `Description`) VALUES ('Trilho da Preguiça', 'trilhopreguica.png', '41.75072103241878', '-8.152548190298736', '0', 'Pretende proporcionar ao visitante não só um contacto direto com a natureza, mas também, despertar o sentimento de pertença à comunidade envolvente e estimular a vontade pelo saber.');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('1', '1');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('3', '2');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('1', '3');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('14', '4');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('6', '5');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('9', '6');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('14', '7');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('16', '8');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('13', '9');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('1', '10');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('1', '11');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('2', '12');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('8', '13');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('13', '14');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('1', '15');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('17', '16');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('17', '17');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('17', '18');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('17', '19');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('15', '20');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('13', '21');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('17', '22');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('1', '23');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('13', '24');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('2', '25');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('12', '26');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('14', '27');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('13', '28');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('1', '29');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('17', '30');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('8', '31');
INSERT INTO `geres4udb`.`pointofinterestcategory` (`CategoryID`, `PointOfInterestID`) VALUES ('18', '32');
